sudo: required
services:
  - docker


before_install:
  - docker build -t 4ever7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 4ever7/react-test npm test -- --coverage

# after success will go through each of the sub-folders and build
# the containers specified by the default "Dockerfile"
after_success:
  - docker build -t 4ever7/multi-client ./client
  - docker build -t 4ever7/multi-nginx ./nginx
  - docker build -t 4ever7/multi-server ./server
  - docker build -t 4ever7/multi-worker ./worker 

# Push built containers to docker hub
#
# Log in the docker CLI
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin

# Take the images and push up to docker hub
  - docker push 4ever7/multi-client
  - docker push 4ever7/multi-nginx
  - docker push 4ever7/multi-server
  - docker push 4ever7/multi-worker
